permalink: /posts/:year/:month/:day/:title.html

exclude: [".ruby-version", ".ruby-gemset", "Gemfile", "Gemfile.lock", "README.md", "CNAME", "package.json", "build.js", "node_modules"]
markdown: kramdown
highlighter: pygments

sass:
  style: :compressed

title: The Nerd Archive
author:
  name: Latchezar Tzvetkoff
  email: latchezar&lt;foo&gt;tzvetkoff&lt;bar&gt;net
  github: tzvetkoff
  twitter: tzvetkoff
  facebook: tzvetkoff

disqus:
  shortname: tzvetkoff

production_url: http://tzvetkoff.net
